spring:
    datasource:
        url: jdbc:postgresql://containers-us-west-133.railway.app:5801/railway
        username: postgres
        password: 8U1PEkLh9OuviRtsaznL
    jpa:
        open-in-view: false
        hibernate:
            #ddl-auto: create
            #ddl-auto: create
            ddl-auto: validate
